export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_LOADING = 'FETCH_MEMBERS_LOADING';
export const FETCH_DSM_DATA_SUCCESS = 'FETCH_DSM_DATA_SUCCESS';
export const FETCH_DSM_DATA_LOADING = 'FETCH_DSM_DATA_LOADING';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const CURRENT_MEMBER_INDEX_SUCCESS = 'CURRENT_MEMBER_INDEX_SUCCESS';